import type { CVTemplate } from './cvTypes'

export const CV_TEMPLATES: CVTemplate[] = [
  {
    id: 'cv-ausbildung-classic',
    name: 'CV Ausbildung Allemagne classique',
    shortName: 'Ausbildung Classique',
    category: 'Formation Allemagne',
    objectiveHints: ['general_allemagne', 'emploi_stage'],
    layout: 'classic',
    accent: '#1f4e79',
    secondary: '#eef5fb',
    withPhoto: true,
    description: 'CV sérieux, propre et administratif pour dossiers de formation professionnelle en Allemagne.',
    bestFor: ['Ausbildung', 'dossier ambassade', 'profil scolaire clair'],
    sections: ['Profil', 'Formation', 'Expériences', 'Langues', 'Compétences']
  },
  {
    id: 'cv-aupair-modern',
    name: 'CV Au Pair moderne',
    shortName: 'Au Pair Moderne',
    category: 'Au Pair',
    objectiveHints: ['au_pair'],
    layout: 'sidebar',
    accent: '#b45309',
    secondary: '#fff7ed',
    withPhoto: true,
    description: 'Modèle chaleureux pour valoriser la garde d’enfants, la famille, les langues et la motivation.',
    bestFor: ['Au Pair', 'expérience avec enfants', 'famille d’accueil'],
    sections: ['Profil', 'Garde d’enfants', 'Formation', 'Langues', 'Centres d’intérêt']
  },
  {
    id: 'cv-fsj-bfd-social',
    name: 'CV FSJ/BFD social',
    shortName: 'FSJ/BFD Social',
    category: 'Volontariat',
    objectiveHints: ['fsj_bfd'],
    layout: 'timeline',
    accent: '#047857',
    secondary: '#ecfdf5',
    withPhoto: true,
    description: 'CV orienté engagement social, maison de retraite, hôpital, crèche ou association.',
    bestFor: ['FSJ', 'BFD', 'service volontaire', 'domaine social'],
    sections: ['Profil', 'Stages sociaux', 'Expériences', 'Formation', 'Langues']
  },
  {
    id: 'cv-pflegefachfrau',
    name: 'CV Pflegefachfrau/Pflegefachmann',
    shortName: 'Pflege',
    category: 'Soins infirmiers',
    objectiveHints: ['ausbildung_pflege'],
    layout: 'cards',
    accent: '#be123c',
    secondary: '#fff1f2',
    withPhoto: true,
    description: 'Modèle professionnel pour une candidature en soins infirmiers ou aide-soignante.',
    bestFor: ['Pflegefachfrau', 'Pflegefachmann', 'aide-soignante', 'hôpital'],
    sections: ['Profil soins', 'Stages', 'Expériences', 'Certificats', 'Langues']
  },
  {
    id: 'cv-gastronomie-koch',
    name: 'CV Gastronomie/Koch',
    shortName: 'Cuisine',
    category: 'Cuisine',
    objectiveHints: ['gastronomie_koch'],
    layout: 'sidebar',
    accent: '#7c2d12',
    secondary: '#fff7ed',
    withPhoto: true,
    description: 'CV adapté aux profils cuisine, restaurant, service, commis ou Ausbildung Koch/Köchin.',
    bestFor: ['Koch/Köchin', 'restaurant', 'cuisine', 'service'],
    sections: ['Profil cuisine', 'Expériences', 'Stages', 'Compétences pratiques', 'Langues']
  },
  {
    id: 'cv-hotellerie',
    name: 'CV Hotellerie',
    shortName: 'Hôtellerie',
    category: 'Hôtellerie',
    objectiveHints: ['hotellerie'],
    layout: 'premium',
    accent: '#4338ca',
    secondary: '#eef2ff',
    withPhoto: true,
    description: 'Design élégant pour réception, service hôtelier, restauration et tourisme.',
    bestFor: ['hôtel', 'réception', 'service', 'tourisme'],
    sections: ['Profil', 'Expériences', 'Formation', 'Compétences service', 'Langues']
  },
  {
    id: 'cv-kita-education',
    name: 'CV Kita/Éducation enfantine',
    shortName: 'Kita',
    category: 'Éducation',
    objectiveHints: ['kita_education', 'au_pair', 'fsj_bfd'],
    layout: 'cards',
    accent: '#0f766e',
    secondary: '#f0fdfa',
    withPhoto: true,
    description: 'CV pour crèche, maternelle, garde d’enfants, éducation et animation.',
    bestFor: ['crèche', 'maternelle', 'garde d’enfants', 'éducation'],
    sections: ['Profil enfants', 'Expériences', 'Stages', 'Formation', 'Qualités']
  },
  {
    id: 'cv-debutant-sans-experience',
    name: 'CV Débutant sans expérience',
    shortName: 'Débutant',
    category: 'Débutant',
    objectiveHints: ['general_allemagne', 'emploi_stage'],
    layout: 'minimal',
    accent: '#334155',
    secondary: '#f8fafc',
    withPhoto: true,
    description: 'Modèle simple qui valorise la formation, les langues, les qualités et les objectifs.',
    bestFor: ['BAC récent', 'peu d’expérience', 'première candidature'],
    sections: ['Objectif', 'Formation', 'Langues', 'Compétences', 'Centres d’intérêt']
  },
  {
    id: 'cv-etudiant-stages',
    name: 'CV Étudiant avec stages',
    shortName: 'Étudiant + Stages',
    category: 'Étudiant',
    objectiveHints: ['emploi_stage', 'general_allemagne'],
    layout: 'timeline',
    accent: '#2563eb',
    secondary: '#eff6ff',
    withPhoto: true,
    description: 'Très bon choix pour un profil scolaire avec quelques stages ou expériences courtes.',
    bestFor: ['étudiant', 'stages', 'formation en cours'],
    sections: ['Profil', 'Formation', 'Stages', 'Compétences', 'Langues']
  },
  {
    id: 'cv-professionnel-experimente',
    name: 'CV Professionnel expérimenté',
    shortName: 'Expérimenté',
    category: 'Professionnel',
    objectiveHints: ['emploi_stage', 'administration_comptabilite', 'informatique_digital'],
    layout: 'premium',
    accent: '#111827',
    secondary: '#f3f4f6',
    withPhoto: false,
    description: 'CV mature pour candidats ayant plusieurs expériences professionnelles.',
    bestFor: ['plusieurs emplois', 'responsabilités', 'parcours professionnel'],
    sections: ['Résumé', 'Expériences', 'Compétences clés', 'Formation', 'Certificats']
  },
  {
    id: 'cv-allemagne-sobre-photo',
    name: 'CV Allemagne sobre avec photo',
    shortName: 'Allemand sobre',
    category: 'Allemagne',
    objectiveHints: ['general_allemagne', 'ausbildung_pflege', 'fsj_bfd'],
    layout: 'classic',
    accent: '#0f172a',
    secondary: '#f1f5f9',
    withPhoto: true,
    description: 'Design sobre et rassurant, adapté aux documents officiels allemands.',
    bestFor: ['ambassade', 'employeur allemand', 'candidature formelle'],
    sections: ['Persönliche Daten', 'Schulbildung', 'Praktika', 'Sprachkenntnisse', 'Kenntnisse']
  },
  {
    id: 'cv-allemagne-sans-photo',
    name: 'CV Allemagne sans photo',
    shortName: 'Sans photo',
    category: 'International',
    objectiveHints: ['general_allemagne', 'emploi_stage'],
    layout: 'minimal',
    accent: '#1e293b',
    secondary: '#f8fafc',
    withPhoto: false,
    description: 'Version neutre et internationale, sans photo, avec mise en page claire.',
    bestFor: ['sans photo', 'candidature neutre', 'format international'],
    sections: ['Profil', 'Formation', 'Expériences', 'Langues', 'Compétences']
  },
  {
    id: 'cv-bilingue-fr-de',
    name: 'CV bilingue Français-Allemand',
    shortName: 'Bilingue FR-DE',
    category: 'Bilingue',
    objectiveHints: ['general_allemagne', 'au_pair', 'fsj_bfd', 'ausbildung_pflege'],
    layout: 'bilingual',
    accent: '#6d28d9',
    secondary: '#f5f3ff',
    withPhoto: true,
    description: 'CV avec intitulés en français et allemand pour montrer la compréhension des deux langues.',
    bestFor: ['élève germanophone', 'dossier Allemagne', 'présentation bilingue'],
    sections: ['Profil / Profil', 'Formation / Ausbildung', 'Expériences / Erfahrungen', 'Langues / Sprachen']
  },
  {
    id: 'cv-comptabilite-administration',
    name: 'CV Comptabilité/Administration',
    shortName: 'Administration',
    category: 'Bureau',
    objectiveHints: ['administration_comptabilite'],
    layout: 'cards',
    accent: '#0369a1',
    secondary: '#f0f9ff',
    withPhoto: true,
    description: 'CV pour gestion, secrétariat, comptabilité, accueil et administration.',
    bestFor: ['comptabilité', 'secrétariat', 'gestion', 'bureau'],
    sections: ['Profil administratif', 'Expériences', 'Formation', 'Compétences bureautiques', 'Langues']
  },
  {
    id: 'cv-informatique-digital',
    name: 'CV Informatique/Digital',
    shortName: 'Digital',
    category: 'Digital',
    objectiveHints: ['informatique_digital'],
    layout: 'sidebar',
    accent: '#4f46e5',
    secondary: '#eef2ff',
    withPhoto: false,
    description: 'Modèle moderne pour informatique, bureautique, web, design et digital.',
    bestFor: ['informatique', 'web', 'digital', 'bureautique avancée'],
    sections: ['Profil', 'Projets/Expériences', 'Compétences techniques', 'Formation', 'Langues']
  },
  {
    id: 'cv-creatif-moderne',
    name: 'CV Créatif moderne',
    shortName: 'Créatif',
    category: 'Moderne',
    objectiveHints: ['emploi_stage', 'general_allemagne'],
    layout: 'cards',
    accent: '#db2777',
    secondary: '#fdf2f8',
    withPhoto: true,
    description: 'Design visuel, moderne et élégant sans perdre le sérieux professionnel.',
    bestFor: ['profil polyvalent', 'présentation moderne', 'créatif'],
    sections: ['Profil', 'Parcours', 'Expériences', 'Compétences', 'Langues']
  },
  {
    id: 'cv-europass-ameliore',
    name: 'CV Europass amélioré',
    shortName: 'Europass+',
    category: 'Europass',
    objectiveHints: ['general_allemagne', 'emploi_stage'],
    layout: 'european',
    accent: '#164e63',
    secondary: '#ecfeff',
    withPhoto: true,
    description: 'Structure proche Europass, mais plus lisible et plus élégante.',
    bestFor: ['format européen', 'dossier officiel', 'parcours détaillé'],
    sections: ['Informations personnelles', 'Expérience', 'Éducation', 'Compétences', 'Langues']
  },
  {
    id: 'cv-chronologique-simple',
    name: 'CV chronologique simple',
    shortName: 'Chronologique',
    category: 'Simple',
    objectiveHints: ['general_allemagne', 'emploi_stage'],
    layout: 'timeline',
    accent: '#475569',
    secondary: '#f8fafc',
    withPhoto: true,
    description: 'Mise en valeur claire des dates, de l’école aux expériences.',
    bestFor: ['parcours scolaire', 'dates importantes', 'simplicité'],
    sections: ['Profil', 'Chronologie', 'Formation', 'Expériences', 'Langues']
  },
  {
    id: 'cv-competences-first',
    name: 'CV compétences avant expériences',
    shortName: 'Compétences+',
    category: 'Compétences',
    objectiveHints: ['emploi_stage', 'general_allemagne'],
    layout: 'compact',
    accent: '#15803d',
    secondary: '#f0fdf4',
    withPhoto: true,
    description: 'Idéal quand le candidat a peu d’expérience, mais de bonnes compétences transférables.',
    bestFor: ['peu d’expérience', 'compétences fortes', 'reconversion'],
    sections: ['Compétences clés', 'Profil', 'Formation', 'Stages', 'Langues']
  },
  {
    id: 'cv-premium-une-page',
    name: 'CV premium une page',
    shortName: 'Premium 1 page',
    category: 'Premium',
    objectiveHints: ['general_allemagne', 'emploi_stage', 'hotellerie'],
    layout: 'premium',
    accent: '#92400e',
    secondary: '#fffbeb',
    withPhoto: true,
    description: 'Version courte, élégante, très lisible et adaptée aux dossiers haut de gamme.',
    bestFor: ['CV court', 'présentation premium', 'profil bien synthétisé'],
    sections: ['Résumé', 'Expériences principales', 'Formation', 'Langues', 'Compétences']
  }
]

export function getTemplateById(id?: string | null): CVTemplate {
  return CV_TEMPLATES.find((template) => template.id === id) ?? CV_TEMPLATES[0]
}
